name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: |
          docker build -t tetris-game .

      - name: Start services
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run unit tests
        run: |
          docker-compose exec -T tetris pytest test/unit_tests

      - name: Run feature tests
        run: |
          docker-compose exec tetris behave test/features

      - name: Stop services
        run: docker-compose down